import './js-modules/main-page-default';
import './js-modules/genres';
import './js-modules/render-header';
import './js-modules/loader'
import './js-modules/modal-footer'
import './js-modules/login-modal';
import './js-modules/authentication-login';
import './js-modules/authentication-sign';
import './js-modules/is-auth';
